### ISSUE TITLE
Please use release tags to help with versioning

### ISSUE THREAD

**Issue by JohnAD** [juancarlospaco/webgui#1]
I just installed a project that is using `webgui` and got compiler errors. The `.nimble` file for that project required `webgui` version `0.1.0`. I was able to figure out that the version `0.1.0` in my computer is on an older commit than the current version `0.1.0`. So, I upgraded to the new `0.1.0`. I'm still getting errors, but they are different ones now.

I recommend adding using the _release_ function of GitHub so that the official version `0.1.0` is pointing to a specific commit.

Or, roll the release number in `webgui.nimble` to `0.1.1` and create a `0.1.1` release pointing to the current commit number.

**Comment by juancarlospaco** [comment]
https://github.com/juancarlospaco/webgui/releases/tag/0.2.0
