### ISSUE TITLE
using karax with webgui?

### ISSUE THREAD

**Issue by sdmcallister** [juancarlospaco/webgui#12]
If I create a view using karax, is there any way to re-use that in webgui?

**Comment by juancarlospaco** [comment]
Yes, thats the idea, you can do that. I will not add Karax as dependency tho.

You can also use source code filters and one of those:
- https://juancarlospaco.github.io/grabulma
- https://juancarlospaco.github.io/grapespectre

Thats up to your creativity :slightly_smiling_face:
