### ISSUE TITLE
Maximized wins

### ISSUE THREAD

**Issue by archnim** [juancarlospaco/webgui#13]
Hello world ! It seems impossible to maximize windows at startup. Please, is it possible to add that feature ? Or is it me that ignore how to do it ?

**Comment by juancarlospaco** [comment]
https://juancarlospaco.github.io/webgui/#newWebView%2Cstatic%5Bstring%5D%2Cstring%2CPositive%2CPositive%2Cstatic%5Bbool%5D%2Cstatic%5Bbool%5D%2CExternalInvokeCb%2Cstatic%5Bbool%5D%2Cstatic%5Bbool%5D%2Cstatic%5Bbool%5D%2Cstatic%5Bbool%5D%2Cstatic%5Bbool%5D%2Cstatic%5Bstring%5D%2Cstatic%5Bcstring%5D%2Cstatic%5Bbool%5D

You can set the size, focus and fullscreen.
But be careful about forcing it on all users, not everyone may want that.

**Comment by archnim** [comment]
Thank you very much. How can i set the size of the window to that of the device's screen? What to do, if I don't wont my window to be centered on the screen, if I wont it to fill the whole screen, without being in fullscreen mode(which hides the title and top buttons).

**Comment by archnim** [comment]
On windows, the user can maximize the window by clicking on the square button. But to put the window in fullscreen, they usually press f11. With webgui, we can set fullscreen programmatically. Know, what about adding the maximization feature? 🙂

**Comment by archnim** [comment]
My English level is too low explain what I have in mind 😕. If only you understood french!

**Comment by juancarlospaco** [comment]
With the current wrapper, is the limits of what can be done, sorry.

And upstream rewrote all to weird and complex C++, is as far as it gets.

**Comment by archnim** [comment]
Ok. I understand.

**Comment by archnim** [comment]
What about joining our efforts, and create a real full-featured nimlang gui framework, that doesn't depend on any C or C++ lib? We can even ask for help on Nim forum....
I'm really enthusiastic about that 😀🤓

**Comment by archnim** [comment]
We can use nim-csfml. It uses C under the hood, but it doesn't matter. 😉
Do you find it interesting? Do you want us to continue this conversation in our Twitter inbox?
