### ISSUE TITLE
dataUriHtmlHeader should consistent with WEBVIEW_DATA_URL_PREFIX otherwise load from html string not work

### ISSUE THREAD

**Issue by bung87** [juancarlospaco/webgui#17]
https://github.com/juancarlospaco/webgui/blob/bcd58620dc84c2d8520f63c4bccf7289256caeea/src/webgui.nim#L314

**Comment by juancarlospaco** [comment]
I do not understand the Bug report, 
but Pull Requests welcome, maybe it is even faster than explaining it to me... 🙂

**Comment by bung87** [comment]
```
isDataURL = (strncmp(webview_url, WEBVIEW_DATA_URL_PREFIX,
                         strlen(WEBVIEW_DATA_URL_PREFIX)) == 0);
```
will be fails in current implementation.

**Comment by bung87** [comment]
`data:text/html,` compare to `data:text/html;....`

**Comment by juancarlospaco** [comment]
Sorry I dont get it, if you understand it maybe just send the Pull Request and will be merged.

**Comment by juancarlospaco** [comment]
Feel free to send PR @bung87 
I dont fully understand your problem sorry, but I can merge the fix. 🙂
