### ISSUE TITLE
Question: Can you use relative filepaths for HTML files? If not, how could you ship an application using webgui?

### ISSUE THREAD

**Issue by PhilippMDoerner** [juancarlospaco/webgui#18]
I recently started playing around with webgui and must say I like it quite a bit.
From what I gather, basically just write an SPA, throw it together with webgui and ship it, you can use the OS' JS/HTML/CSS engines and your own webserver, which should cut down application size by like 1 entire Browser and a second JS engine compared to electron.

My thoughts soon turned towards how I would ship an application with webgui though if I were to make one. 
Something that caused issues there was the fact that file-paths are determined at compile-time instead of at runtime, combined with the fact that they appear to be absolute (?).
I'm actually not that certain about the "absolute" part, but I couldn't manage getting relative filepaths to work and the docs appear to support my assumption ( `path is the URL **or Full Path** to 1 HTML file, index of the Web GUI App.`).
Anyway, my worry is, that if my application uses absolute filepath X that gets hard-coded at compiletime, then I can't just package the binary + HTML file into a folder (e.g. `/home/karl/potatofolder`) and chuck it somewhere on another user's drive (e.g. `home/klaus/potato`), the path to that folder might be different on that user's machine, even though the relative filepaths of the index.html to the binary stayed the same! 
If I could instruct the binary basically to just say "do not care about the path, the HTML file is in the same folder as you" that would alleviate my worries there.

Otherwise the only thing I could think of to ship a webgui application would be to ship it in a docker container or somesuch which come with their own file-system that I can do with whatever I want. Feels somewhat odd though.

**Comment by juancarlospaco** [comment]
> From what I gather, basically just write an SPA, throw it together with webgui and ship it, you can use the OS' JS/HTML/CSS engines and your own webserver, which should cut down application size by like 1 entire Browser and a second JS engine compared to electron.

Yeah, you get it!. 🥳

 
> My thoughts soon turned towards how I would ship an application with webgui though if I were to make one. 

Like this you mean ?

- https://github.com/ThomasTJdev/choosenim_gui/blob/master/src/choosenimgui.nim#L4
- https://github.com/ThomasTJdev/nim_nimble_gui/blob/master/src/nimblegui.nim#L3-L7
- https://github.com/juancarlospaco/borapp/blob/master/src/borapp.nim#L35

**Comment by PhilippMDoerner** [comment]
I just saw your second example using staticRead and I think I had a minor Eureka moment.

So the current impression I'm under is that **the HTML gets basically read in and built into the binary**. There is no need for a runtime path fort the binary because the entire HTML string is already included in the binary. Which is a **way** better idea for the problem, I could facepalm to no end I didn't realize this.

Now that leads me to my next question, does that include the JS files that one would normally link to via script-tags on a normal webpage?
Like, take for example this angular index.html:
```html
<!DOCTYPE html><html lang="en">
<head> <---Irrelevant head stuff---></head>
<body>
  <h1>Image Stable</h1>
  <app-root></app-root>
<script src="runtime.18f9466c9ed22f5d.js" type="module"></script><script src="polyfills.f3ccc8bd29b7591c.js" type="module"></script><script src="main.3aa38e9bffa7ccbe.js" type="module"></script>

</body></html>
```

How do I need to deal with this so that the JS gets loaded properly? Do I need to copy paste the contents of the `runtime.*.js`, `polyfills.*.js`  etc. files into the index.html file so that it gets loaded properly: `<scrip> <FILE_CONTENT> </script>` ?
Or does the binary just need to be in the same folder as the JS files?

I'm already aware that for the CSS I can determine a separate path, just trying to see how that works for JS.

**Comment by juancarlospaco** [comment]
Works the same, you can also inject JS with `js("")` and CSS with `css("")`:

https://github.com/juancarlospaco/webgui/blob/master/src/webgui.nim#L193-L194

**Comment by juancarlospaco** [comment]
For the CSS, the default style is decent, for complex stuff I recommend using Bulma.

For the JS, use Nim targeting JS and https://github.com/juancarlospaco/nodejs

**Comment by PhilippMDoerner** [comment]
> For the CSS, the default style is decent, for complex stuff I recommend using Bulma.
> 
> For the JS, use Nim targeting JS and https://github.com/juancarlospaco/nodejs

I have some pretty decent knowledge of Angular and its technologies, particularly how its fairly easy to structure an Angular SPA well, so I'll work on getting that functional first I think and set up some pipeline that updates my code automatically to load the corresponding JS and CSS files it compiles.

Overall though, I think the js and css procs are likely going to solve what I had in mind, thank you very much for those! 
I just need to figure out a way that I don't have to adjust the filepath name all the time.

**Comment by juancarlospaco** [comment]
Just `staticRead` everything and use it as `string`, use a minifier for release build.

The `js("")` and `css("")` dont care how you get the `string`, so thats up to you.

**Comment by juancarlospaco** [comment]
So looks like nothing really critical is happening here, so closing for now...
