### ISSUE TITLE
Bootstrap/Tailwind support

### ISSUE THREAD

**Issue by yaroslav-gwit** [juancarlospaco/webgui#19]
Your project looks really interesting.
I haven't tried to use anything advanced with it yet, but would it be possible to integrate Bootstrap or Tailwind into the app?

Bare/GTK html styles don't look as good as Tailwind or Bootstrap, hence why I am asking.

**Comment by juancarlospaco** [comment]
Bootstrap already works.
I dont know Tailwinds, but should.
Simply link it and use it. 🙂

**Comment by yaroslav-gwit** [comment]
Thanks :)

Just tried BS5, which seems to be working fine, but with 1 small issue: it's picking up the default GTK theme colours (something I want to avoid this time). Is there a way to switch that feature off?

**Comment by juancarlospaco** [comment]
You would have to theme everything up with the CSS framework.
Works for me with Bulma and Karax.

**Comment by yaroslav-gwit** [comment]
Great, thanks. Had to add `.bg-dark` to the `body` tag, now everything looks just as it should.

**Comment by juancarlospaco** [comment]
Cool!, yeah styling works, you just gotta tinker with it...
If doing a lot of Frontend/JS stuff also check https://github.com/juancarlospaco/nodejs
🙂

**Comment by yaroslav-gwit** [comment]
Thanks, I've starred your NodeJS repo too, will dive deeper once I have some time for it.

By the way, to avoid rewriting all items styles, you can reload the window using JS like so (reload once on app startup):
```
window.onload = function() {
    if(!window.location.hash) {
        window.location = window.location + '#loaded';
        window.location.reload();
    }
}
```

That way it's easier to use BS5/Tailwind/Bulma native and default styling :)
