### ISSUE TITLE
Can't import on MacOS Catalina

### ISSUE THREAD

**Issue by agucova** [juancarlospaco/webgui#4]
Hi! I was trying to run the examples made by ThomasTJdev, and after not being able to run any of the examples, I narrowed the problem to the first line.

> import webgui

It seems this makes clang show a lot of errors that I can't even begin to debug. (Nim beginner here!).

I made [this](https://gist.github.com/agucova/8a433e74671fe576177bd33d8b0a277e) gist with the build log on my machine.

I'm using the latest WebGUI from Nimble (0.4.0), and I'm running Nim 1.2.0 installed by Homebrew in MacOS Catalina 10.15.3. Can try any suggestions if needed.

**Comment by juancarlospaco** [comment]
Try `nim objc` instead of `nim c` ?.
It needs Webkit and Cocoa and related development libs for those.

**Comment by agucova** [comment]
Running `nim objc minimal.nim` gives the exact same errors:

```
webview.h:1717:23: error: too many arguments to function call, expected 0, have 3
  return objc_msgSend((id)objc_getClass("NSString"),
```

**Comment by bung87** [comment]
`--passC="-DOBJC_OLD_DISPATCH_PROTOTYPES=1"`  using c compiler is fine, it will switch objective-c , I successfully runs a simple demo.

**Comment by juancarlospaco** [comment]
Can you send PR ?, I will merge.
(No Mac here).

**Comment by bung87** [comment]
you mean embedding flag to source ? yeah, I can do it.

**Comment by juancarlospaco** [comment]
Yes.
