### ISSUE TITLE
Linking on Windows fails: undefined reference to ShellExecute

### ISSUE THREAD

**Issue by ZoomRmc** [juancarlospaco/webgui#8]
Linking on Windows fails with `undefined reference to ShellExecute` errors.

Possible source:
https://github.com/juancarlospaco/webgui/blob/820cedce57adc5db24a3a9d9056110244657e32c/src/webview.h#L1502 Should it be ` ShellExecuteW`?
Secondly, `-lcomdlg32` isn't passed to the linker, otherwise a bunch of errors pop up for `tinyfiledialogs`.

**Comment by juancarlospaco** [comment]
@ZoomRmc Can you send PR with the mentioned changes?, I will merge.
I dont have Windows myself right now.
